### ISSUE TITLE
Theme displays weird colors in emacsclient

### ISSUE THREAD

**Issue by corentincam** [cqql/xresources-theme#6]
When I start emacsclient, theme is loaded but displays weird colors (some fine colors, some coming from nowhere), until I make emacs eval .emacs manually.

![capture d ecran de 2018-01-17 16-16-08](https://user-images.githubusercontent.com/26230177/35049932-dc63ead0-fba1-11e7-94ec-7978a66beadb.png)

![capture d ecran de 2018-01-17 16-17-25](https://user-images.githubusercontent.com/26230177/35049987-0111d7f2-fba2-11e7-8cae-cf0d222d03b6.png)

**Comment by martenlienen** [comment]
Have you tried evaluating your init.el expression by expression? It would be helpful to know, which part exactly is responsible for the correction.

One idea that I have is that maybe your emacs server is started before the Xresources DB is loaded, so that the theme is loaded with default colors and once you reevaluate your init.el the correct values are read from the environment of your client. However, I have never used emacs client, so I don't know if that is how it works.

**Comment by corentincam** [comment]
That's exactly what you were thinking, .emacs file is evaluated before opening the GUI frame, so the theme can not be loaded.
It can be fixed by replacing
`(load-theme 'xresources t)`
by
`(add-hook 'after-make-frame-functions (lambda (frame) (load-theme 'xresources t)))`
